# Generated by Django 4.0.4 on 2022-05-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('playing_song_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('main_hit', models.FileField(upload_to='songs/')),
                ('song_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('songs', models.FileField(upload_to='songs/')),
            ],
        ),
    ]
