# Generated by Django 4.0.4 on 2022-05-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juiceApp', '0002_home_song_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='song_name2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='song_name3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='song_name4',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='song_name5',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='song_name6',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='song_name7',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='songs2',
            field=models.FileField(default='DEFAULT VALUE', upload_to='songs/'),
        ),
        migrations.AddField(
            model_name='home',
            name='songs3',
            field=models.FileField(default='DEFAULT VALUE', upload_to='songs/'),
        ),
        migrations.AddField(
            model_name='home',
            name='songs4',
            field=models.FileField(default='DEFAULT VALUE', upload_to='songs/'),
        ),
        migrations.AddField(
            model_name='home',
            name='songs5',
            field=models.FileField(default='DEFAULT VALUE', upload_to='songs/'),
        ),
        migrations.AddField(
            model_name='home',
            name='songs6',
            field=models.FileField(default='DEFAULT VALUE', upload_to='songs/'),
        ),
        migrations.AddField(
            model_name='home',
            name='songs7',
            field=models.FileField(default='DEFAULT VALUE', upload_to='songs/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='main_hit',
            field=models.FileField(blank=True, null=True, upload_to='songs/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='songs',
            field=models.FileField(default='DEFAULT VALUE', upload_to='songs/'),
        ),
    ]
